### ISSUE TITLE
SRC_IP Extraction for SSH Logins. 

### ISSUE THREAD

**Issue by ghost** [doksu/TA-linux_secure#1]
Hi 

Thanks for the TA. I am finding it is not extraction SRC_IP although specified in this stanza. 

[sshd_auth]
REGEX = (\S+) (\S+) for (\S+) from (\S+) port (\d+) ([^\:]+)(?:: (\S+) (\S+))?
FORMAT = vendor_action::$1 auth_method::$2 user::$3 src_ip::$4 src_port::$5 ssh_protocol::$6 algorithm::$7 public_key_fingerprint::$8

Regex is valid but not working. Il seek to resolve but just for tracking. 

Version 0.1.3. 

Cheers, 

Paul

**Comment by doksu** [comment]
Hi @butlermonkey,

Thanks very much for making contact. Would you mind sharing the OS that produced the log event that isn't being parsed correctly (e.g. RHEL 7.4) and if possible a sample log event (redacted as necessary).

Cheers,
Doug

**Comment by ghost** [comment]
Hi 

Sure release is Centos 6.9. 

The log that seems not to work is this:

"Dec 17 17:23:59 ip-172-31-47-14 sshd[24952]: Accepted password for centos from 172.31.33.191 port 53582 ssh2"

I tried the Splunk_TA_nix and this works ok. 

Regex 101 shows your regex matching and group ok but it does not extract. 

This one in Splunk_TA_nix uses: 

REGEX = (sshd)\[\d+\]\:\s+(?:\[[^]]+]\s+)?.*?(Accepted|Failed|failure|(?:Invalid user)).*?(\S+)\s+from.*?(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?:\s+port\s+(\S+)\s+\w?\s*(ssh\d))?
FORMAT = app::$1 vendor_action::$2 user::$3 src_ip::$4 src_port::$5 sshd_protocol::$6

Which works in Splunk but not in regex 101.

Hope this helps.

**Comment by doksu** [comment]
Hmm, I've got hosts producing events with the same format and the extractions are working. What version of Splunk is being used in your search environment? (The vendor may have changed something about the way they apply regexes in a recent release of Splunk).

**Comment by rvaglid** [comment]
Hi, I'm also experiencing the same issue, in two different deployments (latest Debian and RHEL 7.4).
The search inspector also throws this warning in both occasions:
_The term '"for * from * port"' contains a wildcard in the middle of a word or string. This might cause inconsistent results if the characters that the wildcard represents include punctuation._ 

I guess the following REGEX in transforms.conf is the culprit:
[sshd_auth]
REGEX = (\S+) (\S+) for (\S+) from (\S+) port (\d+) ([^\:]+)(?:: (\S+) (\S+))?
FORMAT = vendor_action::$1 auth_method::$2 user::$3 src_ip::$4 src_port::$5 ssh_protocol::$6 algorithm::$7 public_key_fingerprint::$8

Please note that src_ip _did_ get extracted correctly in version 0.1.1 of this add-on.

Cheers
Rolf

**Comment by doksu** [comment]
Thanks everyone, I've got a fix in the pipeline that should be released soon.

**Comment by doksu** [comment]
Version 1.0.0 released on Splunkbase with the src_ip extraction issue fixed. Big thanks to Martin Mueller who provided the fixed.
